# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 101) do

  create_table "assets", :force => true do |t|
    t.column "name",   :string,                                 :default => "", :null => false
    t.column "value",  :decimal, :precision => 12, :scale => 2,                 :null => false
    t.column "liquid", :boolean
    t.column "equity", :boolean
  end

  create_table "bank_accounts", :force => true do |t|
    t.column "bank_id", :integer,                                                :null => false
    t.column "number",  :string,                                 :default => "", :null => false
    t.column "name",    :string,                                 :default => "", :null => false
    t.column "balance", :decimal, :precision => 12, :scale => 2,                 :null => false
  end

  create_table "banks", :force => true do |t|
    t.column "name", :string, :default => "", :null => false
  end

  create_table "dividends", :force => true do |t|
    t.column "mutual_fund_investment_id", :integer,                                :null => false
    t.column "value",                     :decimal, :precision => 12, :scale => 4, :null => false
    t.column "date",                      :date,                                   :null => false
  end

  create_table "fixed_deposits", :force => true do |t|
    t.column "bank_id",        :integer,                                :null => false
    t.column "amount",         :decimal, :precision => 10, :scale => 2, :null => false
    t.column "interest_rate",  :decimal, :precision => 4,  :scale => 2, :null => false
    t.column "start_date",     :date,                                   :null => false
    t.column "tenure",         :integer,                                :null => false
    t.column "maturity_date",  :date,                                   :null => false
    t.column "maturity_value", :decimal, :precision => 10, :scale => 2, :null => false
  end

  create_table "mutual_fund_investments", :force => true do |t|
    t.column "mutual_fund_id",     :integer,                                :null => false
    t.column "units",              :decimal, :precision => 12, :scale => 4, :null => false
    t.column "buying_price",       :decimal, :precision => 12, :scale => 4, :null => false
    t.column "buying_value",       :decimal, :precision => 12, :scale => 4, :null => false
    t.column "purchase_date",      :date,                                   :null => false
    t.column "current_value",      :decimal, :precision => 12, :scale => 4
    t.column "sale_price",         :decimal, :precision => 12, :scale => 4
    t.column "sale_value",         :decimal, :precision => 12, :scale => 4
    t.column "sale_date",          :date
    t.column "absolute_returns",   :decimal, :precision => 7,  :scale => 2
    t.column "annualized_returns", :decimal, :precision => 7,  :scale => 2
  end

  create_table "mutual_funds", :force => true do |t|
    t.column "fund_type",   :string,                                 :default => "", :null => false
    t.column "amfi_symbol", :string,                                 :default => "", :null => false
    t.column "name",        :string,                                 :default => "", :null => false
    t.column "nav",         :decimal, :precision => 12, :scale => 4
  end

  create_table "sips", :force => true do |t|
    t.column "mutual_fund_id",     :integer,                                :null => false
    t.column "start_date",         :date,                                   :null => false
    t.column "sip_amount",         :decimal, :precision => 12, :scale => 4, :null => false
    t.column "units",              :decimal, :precision => 12, :scale => 4, :null => false
    t.column "current_value",      :decimal, :precision => 12, :scale => 4
    t.column "absolute_returns",   :decimal, :precision => 7,  :scale => 2
    t.column "annualized_returns", :decimal, :precision => 7,  :scale => 2
  end

end
